### ISSUE TITLE
NZBGeek not working anymore. SceneNZB is working

### ISSUE THREAD

**Issue by RenNagasaki** [PCJones/UmlautAdaptarr#13]
![2](https://github.com/PCJones/UmlautAdaptarr/assets/10595885/570eb400-9b3f-4e08-a17c-be0912c277c9)
![1](https://github.com/PCJones/UmlautAdaptarr/assets/10595885/07383921-3b46-4168-98bf-26836be04924)

Without the Adaptarr it works.

**Comment by PCJones** [comment]
Does restarting the docker container fix it? It's definitely a bug that needs fixing, but I think a restart might fix it for now.

**Comment by PCJones** [comment]
Closed due to lack of response. Feel free to comment again if you still have problems
