### ISSUE TITLE
Jackett?

### ISSUE THREAD

**Issue by Anon0511** [PCJones/UmlautAdaptarr#14]
Anyone got it to work with Jackett? I just tried with one of my Trackers but the Test failed.

**Comment by PCJones** [comment]
Can you share your setup? I don't know Jackett well but I'm pretty sure it should work there

**Comment by Anon0511** [comment]
This is the entry in Jackett for the Tracker. I also tried with http and https and with api/ and without.
![Screenshot 2024-04-03 at 09 21 28](https://github.com/PCJones/UmlautAdaptarr/assets/30687744/4a6e9d67-3b58-4773-ba7f-f8c52b50e006)

The Jackett config for this tracker is here: [Jackett Github](https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/TorrentNetwork.cs)
