### ISSUE TITLE
Ich bin ein Star - Showdown der Dschungel-Legenden (DE) not matched correctly

### ISSUE THREAD

**Issue by schumi4** [PCJones/UmlautAdaptarr#30]
"Ich bin ein Star - Showdown der Dschungel-Legenden (DE)" returns `Unknown Series` for releases like:

- `Ich.bin.ein.Star.Showdown.der.Dschungel-Legenden.S01E02.GERMAN.1080p.WEB.x264-TSCC`
- `Ich.bin.ein.Star.Showdown.der.Dschungel-Legenden.S01E02.GERMAN.1080p.WEB.h264-HAXE`

Import works after manual grab.

[TVDB](https://www.thetvdb.com/series/ich-bin-ein-star-showdown-der-dschungel-legenden-452525)

**Comment by PCJones** [comment]
Caused by duplicate series entry at TVDB:
https://www.thetvdb.com/series/ich-bin-ein-star-showdown-der-dschungel-legenden
https://www.thetvdb.com/series/ich-bin-ein-star-showdown-der-dschungel-legenden-452525

Chose the first one and it will work correctly. Needs to be fixed at TVDB
