### ISSUE TITLE
Good Luck Guys not renamed

### ISSUE THREAD

**Issue by schumi4** [PCJones/UmlautAdaptarr#31]
https://www.thetvdb.com/series/good-luck-guys-germany
no rename/match for `Good.Luck.Guys.S02E01.GERMAN.1080p.WEB.H264-TSCC`

**Comment by PCJones** [comment]
Fixed in https://github.com/PCJones/UmlautAdaptarr/commit/fd6a8581d8974a4e7ee6f7b4ba9bd93638f2d4a6
