### ISSUE TITLE
Bad naming is not corrected (movie example)

### ISSUE THREAD

**Issue by timo-eberl** [PCJones/UmlautAdaptarr#34]
The movie title `Harry.Potter.2009.und.der.Halbblutprinz.Ultimate.Edition.German.DL.1080p.BluRay.x264-LeetHD` does not get corrected. Maybe because the year is (for some reason) inserted in the midst of the title.

Or perhaps this is already corrected by bad naming fix, which I don't know how to enable ( #33 ).

**Comment by timo-eberl** [comment]
Nevermind, my setup does not work at all.

**Comment by PCJones** [comment]
Hi, Radarr is not working yet. I'm currently working on that. Radarr is pretty good in identifying German titles though, I too suspect that the year is the problem here.

Let me know if you need more help :) 

PS: German is fine too
