### ISSUE TITLE
Shopping Queen not matched

### ISSUE THREAD

**Issue by schumi4** [PCJones/UmlautAdaptarr#37]
https://www.thetvdb.com/series/266546-show

Shopping Queen vs. Shopping Queen (DE)

`Shopping.Queen.S2024E2630.Tag.1.Vanessa.Ostfriesland.GERMAN.1080p.WEB.H264-GUiDO`

**Comment by PCJones** [comment]
Fixed https://github.com/PCJones/UmlautAdaptarr/commit/30e1d3aa11b89442aa20a4818382033d40d7e84e
