### ISSUE TITLE
No connection to sonarr since update

### ISSUE THREAD

**Issue by jonas-herkelmedia** [PCJones/UmlautAdaptarr#40]
Connection to sonarr is not working anymore since update.

**Comment by PCJones** [comment]
Please provide logs. Are you using docker or unraid?

**Comment by PCJones** [comment]
Das Problem ist bei vielen Leuten nach dem Update aufgetreten, die die Umgebungsvariablen des Umlautadaptarr nicht korrekt gesetzt hatten. Bitte einmal Schritt 1 der Installationsanleitung überprüfen: https://github.com/PCJones/UmlautAdaptarr#installation

**Comment by PCJones** [comment]
Eine weitere Möglichkeit wäre, dass deine HOST Umgebungsvariablen mit einem / enden - in dem Fall einfach den / am Ende entfernen

**Comment by S2ciOnur** [comment]
Same here.
Ich habe den Umlautadaptarr erst vor einigen Wochen entdeckt.
Meine Umgebungsvariablen habe ich exakt nach der Anleitung eingebettet. Ich habe auch keine / am Ende der URL oder ähnliches.
Es lief alles tadellos.
Seit dem letzten Update bekomme ich folgenden Error:

Error: Could not retrieve public IP Information.

folgen ein paar
The URL "192.168.1.13:30027" is not reachable. Next attempt in 15 seconds...
Das ist die URL von meiner Sonarr instanz, die im Browser jedoch erreichbar ist.
Im Log folgen dann noch ein paar Bemerkungen bzgl. Unhandled exception.
Ich habe das ganze auch mit http:// vor der IP Adresse ausprobiert.
Erfolglos.
Wenn ich die Version auf 0.5 zurück stelle, funktioniert alles wieder.

**Comment by jonas-herkelmedia** [comment]
Habe es leider auch nicht zum Laufen gebracht mit den Tipps und hatte bisher leider keine Zeit es weiter zu testen.
Habe die Version jetzt erstmal zurückgestellt auf 0.5. 
Jetzt am Wochenende kann ich mal versuchen es zu debuggen und gebe dann bescheid mit den genauen Fehlern.

Was interessant ist, dass wenn ich Sonarr 0 und Sonarr 1 als Umgebungsvariablen setze, dass immer Sonarr 1 funktioniert. Also ich kann auch die URL wechseln und er hat dann immer zu der Sonarr Instanz keine Verbindung, die bei Sonarr 0 eingetragen ist.

**Comment by akuntsch** [comment]
Eventuell das gleiche Problem: der reachable Check funktioniert nicht, wenn man in Sonarr etc. Basic Authentication aktiviert hat.

Wäre vielleicht sinnvoller den reachable Check auf ˋ/apiˋ mit ˋx-api-keyˋ Header zu machen. Das gibt selbst bei aktivierter Basic Auth HTTP 200 zurück.

Eventuell hab ich heute Abend mal Zeit das umzubauen, zu testen und einen PR zu erstellen.

**Comment by S2ciOnur** [comment]
Mir ist eben in der PiHole aufgefallen, dass die Anfrage zu ipinfo.io blockiert wird.
Hat vielleicht etwas damit zutun.
Frage mich trotzdem, wieso der Umlautadaptarr meine Geolocation herausfinden will.
Steckt hinter dem Projekt doch eine Behörde?
#AluhutOn

**Comment by S2ciOnur** [comment]
Update von meiner Seite:
Ich habe in meiner Pi-Hole "ipinfo.io" aus der Blockierung aufgehoben.
Die latest Version läuft nun bei mir. 
Hatte wohl mit dem IP Leak test beim init zutun.
Jetzt frag ich mich trotzdem, wieso der Umlautadaptarr meine 
- Public IP
- City
- Region
- Country
- und Provider

sehen will??

**Comment by xpsony** [comment]
Damit Leute wie du Ihre IP Adresse nicht leaken xD.

Ich habe diese Funktion implementiert, damit man beim Startup sehen kann ,ob Gluetun (VPN) korrekt funktioniert.

Da nicht jeder will das seine IP Adresse an die PHP Api oder an die Indexer weitergegeben wird :)

Die Information bleibt bei diesen Test lokal

Mehr Infos findest du wahrscheinlich wenn man nach IP Leak auf Google sucht :)

**Comment by S2ciOnur** [comment]
Der Test ist ja bei mir fehlgeschlagen und der Container konnte anschließend nicht starten.

**Comment by xpsony** [comment]
Ja das ist dann eindeutig ein Bug , ich denke man sollte den IP Leak Test als Umgebungsvariabel deaktivieren bzw. aktivieren können @PCJones . Leider kommt der bei ein paar Leuten leider nicht so gut an wie ich erhofft habe.

Das jemand sein Pihole so stark konfiguriert haben könnte, hätte ich nicht gedacht und ja es ist eine Design Schwäche , soweit ich weiß ,läuft der ins Timeout... . Eventuell sollte man dies etwas entschärfen.

Die allgemeine Idee war halt , das der UmlautAdaptarr beim Starten die Config validiert und lieber abstürzt , als nicht korrekt zu laufen

**Comment by jonas-herkelmedia** [comment]
Bei mir ist das Problem wenn Basic Authentication aktiviert ist, funktioniert es nicht mehr:
The URL "http://sonarr:8989" is not reachable. Next attempt in 15 seconds...

Mit der Version 0.5 ist das kein Problem.

Außerdem sollte man es ermöglichen, dass man den IPleak check deaktivieren kann. Für viele ist dieser unnötig, da man kein VPN für die meisten Indexer benötigt.

**Comment by PCJones** [comment]
0.6.1 ist draußen, danke an @akuntsch 
@S2ciOnur der IP leak test ist jetzt standardmäßig deaktiviert.
@jonas-herkelmedia magst du mal testen ob es jetzt wieder geht?
