### ISSUE TITLE
Error while Register ArrFactory. This might be a Config Problem

### ISSUE THREAD

**Issue by slayerofmadness** [PCJones/UmlautAdaptarr#41]
Hi,

since the 0.6 Update Umlautadaptarr refuses to start and this is the error message...
0.5 works flawless.

I am using the Unraid Template. Can't figure out any problem :(

**Comment by PCJones** [comment]
Can you please remove the template and do a clean reinstall? The template was updated a while ago but sadly doesn't update automatically.

If you still have problems afterwards please share your template settings (you can censor API keys of course)

**Comment by slayerofmadness** [comment]
Ok did a clean reinstall from scratch. The Updated Template also brings me the same error :/

CODE:

<?xml version="1.0"?>
<Container version="2">
  <Name>umlautadaptarr</Name>
  <Repository>pcjones/umlautadaptarr:0.5</Repository>
  <Registry>https://hub.docker.com/r/pcjones/umlautadaptarr/</Registry>
  <Network>host</Network>
  <MyIP/>
  <Shell>sh</Shell>
  <Privileged>false</Privileged>
  <Support>https://discord.gg/pZrrMcJMQM</Support>
  <Project>https://github.com/PCJones/UmlautAdaptarr</Project>
  <Overview>A tool to work around Sonarr, Radarr, Lidarr and Readarr's problems with foreign languages and symbols, like the German umlauts. Don't forget to update the URLs of your indexers in Prowlarr or directly in the used arr apps. Details are found in the documentation.</Overview>
  <Category>Downloaders: MediaApp:Other</Category>
  <WebUI/>
  <TemplateURL>https://raw.githubusercontent.com/tschoerk/unraid-templates/master/umlautadaptarr/umlautadaptarr.xml</TemplateURL>
  <Icon>https://raw.githubusercontent.com/tschoerk/unraid-templates/main/umlautadaptarr/umlaute.png</Icon>
  <ExtraParams/>
  <PostArgs/>
  <CPUset>0,1</CPUset>
  <DateInstalled>1728840929</DateInstalled>
  <DonateText>The dev PCJones is always happy about a donation :D</DonateText>
  <DonateLink>https://paypal.me/pcjones1</DonateLink>
  <Requires/>
  <Config Name="Host Port for 5005" Target="5005" Default="5005" Mode="tcp" Description="" Type="Port" Display="always" Required="true" Mask="false">5005</Config>
  <Config Name="Enable Sonarr" Target="SONARR_ENABLED" Default="false|true" Mode="" Description="" Type="Variable" Display="always" Required="true" Mask="false">true</Config>
  <Config Name="Sonarr Host" Target="SONARR_HOST" Default="http://XXX.XXX.XXX.XXX:8989" Mode="" Description="Host of the Sonarr instance" Type="Variable" Display="always" Required="false" Mask="false">http://192.168.X.X:8989</Config>
  <Config Name="Sonarr API Key" Target="SONARR_API_KEY" Default="" Mode="" Description="The API Key of Sonarr found under Settings-General" Type="Variable" Display="always" Required="false" Mask="false">xxx</Config>
  <Config Name="Enable Radarr" Target="RADARR_ENABLED" Default="false|true" Mode="" Description="" Type="Variable" Display="always" Required="true" Mask="false">true</Config>
  <Config Name="Radarr Host" Target="RADARR_HOST" Default="http://XXX.XXX.XXX.XXX:7878" Mode="" Description="Host of the Radarr instance" Type="Variable" Display="always" Required="false" Mask="false">http://192.168.X.X:7878</Config>
  <Config Name="Radarr API Key" Target="RADARR_API_KEY" Default="" Mode="" Description="The API Key of Radarr found under Settings-General" Type="Variable" Display="always" Required="false" Mask="false">xxx</Config>
  <Config Name="Enable Readarr" Target="READARR_ENABLED" Default="false|true" Mode="" Description="" Type="Variable" Display="always" Required="true" Mask="false">true</Config>
  <Config Name="Readarr Host" Target="READARR_HOST" Default="http://XXX.XXX.XXX.XXX:8787" Mode="" Description="Host of the Readarr instance" Type="Variable" Display="always" Required="false" Mask="false">http://192.168.X.X:8787</Config>
  <Config Name="Readarr API Key" Target="READARR_API_KEY" Default="" Mode="" Description="The API Key of Readarr found under Settings-General" Type="Variable" Display="always" Required="false" Mask="false">xxx</Config>
  <Config Name="Enable Lidarr" Target="LIDARR_ENABLED" Default="false|true" Mode="" Description="" Type="Variable" Display="always" Required="true" Mask="false">true</Config>
  <Config Name="Lidarr Host" Target="LIDARR_HOST" Default="http://XXX.XXX.XXX.XXX:8686" Mode="" Description="Host of the Lidarr instance" Type="Variable" Display="always" Required="false" Mask="false">http://192.168.X.X:8686</Config>
  <Config Name="Lidarr API Key" Target="LIDARR_API_KEY" Default="" Mode="" Description="The API Key of Lidarr found under Settings-General" Type="Variable" Display="always" Required="false" Mask="false">xxx</Config>

**Comment by PCJones** [comment]
That is not the correct template, it's still the outdated one from 6 months ago.
If you have Discord please join us on the [UsenetDE](https://discord.gg/pZrrMcJMQM) server where we have a lot of Unraid users who can help, I don't use Unraid myself.

**Comment by PCJones** [comment]
Here you can see the correct, updated template for unraid:
https://raw.githubusercontent.com/tschoerk/unraid-templates/master/umlautadaptarr/umlautadaptarr.xml

The variables should look like SONARR__ENABLED, with two _

**Comment by slayerofmadness** [comment]
Thank you very much! I will check this out tonight.

Discord bin ich bereits seit längerem dabei auf dem Server, danke für den Hinweis. Muss ich mir genauer ansehen 👍🏻😎

**Comment by slayerofmadness** [comment]
The new template works perfect 😎
