### ISSUE TITLE
API als Repository

### ISSUE THREAD

**Issue by SandraCHC** [PCJones/UmlautAdaptarr#51]
Danke für UmlautAdaptarr. Ich habe zwar des Gefühl das ich unterdessen mehr folgen in Sonarr finde auch ohne Umlautadaptarr aber hiermit finde ich noch immer mehr :D

Gibt es einen Plan, deine API auch als Repository anzubieten? Ich fände es cool diese auch in meinem Docker laufen zu lassen damit die Anfragen nicht nach aussen gehen.
Vielleicht ist es auch nur eine Spielerei aber trotzdem :)

**Comment by PCJones** [comment]
Gibt's einen Grund fürs schließen?

Der API source code ist gerade ziemlicher müll, deshalb ist der noch nicht richtig veröffentlicht. Du kannst ihn aber hier finden und dir daraus einen Docker Container basteln:
https://github.com/PCJones/UmlautAdaptarr/issues/29

**Comment by SandraCHC** [comment]
Bitte entschuldige ich hätte es kommentieren sollen.
Ich habe den Beitrag mit der API bereits gesehen und gedacht das ich dieses issue dann besser gleich schliesse.
Funktioniert auch schon ganz gut damit :)
